services:
  # SQL database
  postgres:
    image: postgres:16.4
    container_name: postgres_social
    environment:
      POSTGRES_DB: ${DB_NAME:-social_db}
      POSTGRES_USER: ${DB_USER:-social_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-social_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Front-end
  www:
    image: reactive-social/www
    build:
      context: ./www
      dockerfile: Dockerfile
    volumes:
      - ./www:/app
    environment:
      REACT_APP_PUBLIC_BACKEND_URL: ${REACT_APP_PUBLIC_BACKEND_URL:-https://localhost/api/}
    command: >
      sh -c "npm install &&
             npm run start"

  # Web application
  web:
    image: reactive-social/web-service
    build:
      context: ./web_service
      dockerfile: Dockerfile
    volumes:
      - ./web_service:/app
    depends_on:
      - postgres
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@admin.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
      DB_NAME: ${DB_NAME:-social_db}
      DB_USER: ${DB_USER:-social_user}
      DB_PASSWORD: ${DB_PASSWORD:-social_password}
      DB_HOST: ${DB_HOST:-postgres}
      REACTIVE_SERVICE_URL: ${REACTIVE_SERVICE_URL:-http://reactive_cache:8081/v1}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py load_initial_data 
             python manage.py runserver 0.0.0.0:3031"

  # Reverse proxy
  haproxy:
    image: haproxy:3.0-alpine3.20
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs/:/etc/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - www
      - web

  # Reactive cache
  reactive_cache:
    image: reactive-social/skip-service
    build: ./reactive_service
    environment:
      POSTGRES_DB: ${DB_NAME:-social_db}
      POSTGRES_USER: ${DB_USER:-social_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-social_password}
      POSTGRES_HOST: ${DB_HOST:-postgres}
    depends_on:
      - web
      - postgres
    entrypoint: >
      sh -c "while ! curl -sSf http://web:3031/api/health/; do
               echo 'Waiting for web to be healthy...';
               sleep 5;
             done;
             echo 'Web is healthy, starting reactive_cache...';
             npm start"

volumes:
  postgres_data:
