# Generated by Django 5.1.3 on 2024-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_owner_serverchannel_serverchannelmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
