# Generated by Django 5.1.3 on 2024-12-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_server_name'),
        ('users', '0003_alter_friendrequest_from_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('profile', 'server')},
        ),
    ]
