# Generated by Django 5.1.3 on 2024-12-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('newbie', 'newbie')], max_length=255),
        ),
        migrations.CreateModel(
            name='ServerChannelAllowedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_roles', to='servers.serverchannel')),
            ],
        ),
    ]
