# Generated by Django 5.1.3 on 2024-11-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='users.profile')),
                ('to_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_profile', 'to_profile'), name='unique_friend_request')],
            },
        ),
    ]
